### ISSUE TITLE
Strange values from fit$fleet.ratio$harv.rate 

### ISSUE THREAD

**Issue by MarcoEnea** [bthe/rgadget#61] opened 2017-02-14 17:42 UTC
When I run fit <- gadget.fit() and then inspect fit$fleet.info I notice that harv.rate can assume values 
greater than 1. Is it possible?

> fit$fleet.info
Source: local data frame [70 x 7]
Groups: year, step, area, fleet [70]

    year  step  area                 fleet       harv.bio         amount            harv.rate
   <int> <int> <dbl>            <fctr>          <dbl>           <dbl>                 <dbl>
1   2002     1     1          commBMT  1625700.0   2379448.4    1.463645e+00
2   2002     1     1            commDP 10874676.2      107551.6    9.890097e-03
3   2002     1     1                survey  1436912.2               93.3    6.493090e-05
4   2002     1     1 TUNcommBMT   1020173.6    1538000.0    1.507587e+00
5   2002     1     1   TUNcommDP 10874676.2                  0.0    0.000000e+00
6   2003     1     1        commBMT  1337630.3      1925937.1    1.439813e+00
7   2003     1     1           commDP  8104348.2         87052.9    1.074151e-02
8   2003     1     1               survey  1356842.0              106.6    7.856478e-05
9   2003     1     1 TUNcommBMT   850947.9      1202000.0    1.412542e+00
10  2003     1     1  TUNcommDP  8104348.2                   0.0    0.000000e+00
# ... with 60 more rows

**Comment by vbartolino** [comment] 2017-02-16 22:08
I suppose understocking could be one of the reasons, but it should be confirmed by others

**Comment by bthe** [comment] 2017-02-17 09:10
There actually a number of reasons for this. It can be as @vbartolino said, i.e. if there is understocking in the model the amounts (which are read from the fleet data file) will be substantially higher than the model biomass. 

Another reason may be linked to the timing of the printing, biomass was set to be printed at the end of the first timestep, not the beginning, this is now fixed in https://github.com/Hafro/rgadget/commit/cb777a9e8f6c98b742d786f0199cfeec87970c11 .

Also note that the printing occurs at the first timestep, and depending on how selection and growthrates are set up, annual catches may exceed the harvestable biomass at the beginning of the year.

**Comment by bthe** [comment] 2017-09-05 15:27
Closing this for now..

**Closed as completed by bthe** 2017-09-05 15:27 UTC
